### ISSUE TITLE
Partiton 

### ISSUE THREAD

**Issue by drmpf** [arduino/uno-r4-wifi-usb-bridge#21] opened 2023-09-18 08:40 UTC
Running the arduino-cli against the esp32-pached install gives the error

```
Error at line 8: Value 'undefined' is not valid. Known keywords: esphttpd, phy, efuse, nvs, fat, spiffs, ota, coredump, nvs_keys
Error during build: exit status 2
```
The patched installed unor4wifi.csv
contains on line 8

`cert,     data, undefined, 0x3C0000,0x040000,`

**Comment by pennam** [comment] 2023-09-18 09:17
@drmpf are you building the firmware on windows? using `0x06` instead of `undefined` should fix the build

**Comment by pennam** [comment] 2023-10-30 08:10
Closing. No feedback from the user and also duplicate of https://github.com/arduino/uno-r4-wifi-usb-bridge/issues/16#issuecomment-1707370214

**Closed by pennam** 2023-10-30 08:10 UTC
